import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { MonthlyData } from '../types';

export const generatePDF = async (monthlyData: MonthlyData) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Header
  pdf.setFontSize(20);
  pdf.setTextColor(59, 130, 246);
  pdf.text('SpendWise - Monthly Report', 20, 25);
  
  // Month
  const [year, month] = monthlyData.month.split('-');
  const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                     'July', 'August', 'September', 'October', 'November', 'December'];
  const monthName = `${monthNames[parseInt(month) - 1]} ${year}`;
  
  pdf.setFontSize(14);
  pdf.setTextColor(107, 114, 128);
  pdf.text(monthName, 20, 35);
  
  // Summary
  pdf.setFontSize(16);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Financial Summary', 20, 50);
  
  pdf.setFontSize(12);
  pdf.setTextColor(34, 197, 94);
  pdf.text(`Total Income: ₹${monthlyData.totalIncome.toFixed(2)}`, 20, 65);
  
  pdf.setTextColor(239, 68, 68);
  pdf.text(`Total Expenses: ₹${monthlyData.totalExpense.toFixed(2)}`, 20, 75);
  
  pdf.setTextColor(monthlyData.balance >= 0 ? 34 : 239, monthlyData.balance >= 0 ? 197 : 68, monthlyData.balance >= 0 ? 94 : 68);
  pdf.text(`Balance: ₹${monthlyData.balance.toFixed(2)}`, 20, 85);
  
  // Category Breakdown
  if (monthlyData.categoryTotals.length > 0) {
    pdf.setFontSize(16);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Expense Breakdown by Category', 20, 105);
    
    let yPos = 120;
    pdf.setFontSize(11);
    
    monthlyData.categoryTotals.forEach((category, index) => {
      pdf.setTextColor(64, 64, 64);
      pdf.text(`${category.category}:`, 25, yPos);
      pdf.text(`₹${category.amount.toFixed(2)}`, pageWidth - 60, yPos);
      pdf.text(`${category.percentage.toFixed(1)}%`, pageWidth - 25, yPos);
      yPos += 8;
      
      if (yPos > pageHeight - 30 && index < monthlyData.categoryTotals.length - 1) {
        pdf.addPage();
        yPos = 30;
      }
    });
  }
  
  // Recent Transactions
  if (monthlyData.transactions.length > 0) {
    if (monthlyData.categoryTotals.length > 0) {
      pdf.addPage();
    }
    
    pdf.setFontSize(16);
    pdf.setTextColor(0, 0, 0);
    pdf.text('Recent Transactions', 20, monthlyData.categoryTotals.length > 0 ? 30 : 130);
    
    let yPos = monthlyData.categoryTotals.length > 0 ? 45 : 145;
    pdf.setFontSize(10);
    
    // Sort transactions by date (newest first)
    const sortedTransactions = [...monthlyData.transactions].sort((a, b) => 
      new Date(b.date).getTime() - new Date(a.date).getTime()
    );
    
    sortedTransactions.forEach((transaction, index) => {
      const date = new Date(transaction.date).toLocaleDateString();
      pdf.setTextColor(64, 64, 64);
      pdf.text(date, 20, yPos);
      pdf.text(transaction.description, 45, yPos);
      pdf.text(transaction.category, 120, yPos);
      
      pdf.setTextColor(transaction.type === 'income' ? 34 : 239, transaction.type === 'income' ? 197 : 68, transaction.type === 'income' ? 94 : 68);
      pdf.text(`${transaction.type === 'income' ? '+' : '-'}₹${transaction.amount.toFixed(2)}`, pageWidth - 30, yPos);
      
      yPos += 6;
      
      if (yPos > pageHeight - 20 && index < sortedTransactions.length - 1) {
        pdf.addPage();
        yPos = 30;
      }
    });
  }
  
  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(156, 163, 175);
  pdf.text('Generated by SpendWise - Personal Spending Analysis', 20, pageHeight - 10);
  pdf.text(new Date().toLocaleDateString(), pageWidth - 40, pageHeight - 10);
  
  // Save the PDF
  pdf.save(`spending-analysis-${monthName.toLowerCase().replace(' ', '-')}.pdf`);
};